#!/usr/bin/env bash

# Based on https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-cht.sh

if (( $# == 0 )) && [[ -n ${TMUX:-} && ${CHEATSHEET_POPUP:-} != 1 ]]; then
  printf -v popup_command 'CHEATSHEET_POPUP=1 %q' "$0"
  tmux display-popup -E -w 65% -h 50% -d '#{pane_current_path}' "$popup_command"
  exit
fi

if [[ ${1:-} == --show ]]; then
  shift
  request=$*
elif (( $# == 0 )); then
  header=$'cheat.sh query syntax\n\nTool page       tar\nTool search     tar~extract archive\nLanguage query  python/reverse a list\nSpecial pages   :help  :list  :learn\n\nPress Enter to search or Esc to close'
  printf -v show_command '%q --show {q}' "$0"

  exec fzf \
    --disabled \
    --layout=default \
    --info=hidden \
    --no-scrollbar \
    --pointer='' \
    --marker='' \
    --border=rounded \
    --border-label=' cheat.sh ' \
    --header="$header" \
    --header-first \
    --header-border=none \
    --input-border=rounded \
    --input-label=' Query ' \
    --prompt='' \
    --ghost='e.g. git~undo last commit' \
    --bind="enter:become($show_command)" < /dev/null
else
  topic=$1
  shift

  if (( $# == 0 )); then
    request=$topic
  else
    query=$*
    if [[ $topic == */ || $topic == *~ ]]; then
      request="${topic}${query}"
    else
      request="${topic}~${query}"
    fi
  fi
fi

[[ -z ${request:-} ]] && exit

request=${request// /+}
curl --globoff -fsSL "https://cht.sh/$request" | less -R
