#! /bin/bash

# NOTE:
# from: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-cht.sh
# with bette tmux capabilities

curl_cht () {
  if [[ -z $TMUX ]]; then
    eval "$1"
  else
    tmux neww bash -c "$1"
  fi
}

languages=`echo "python go javascript typescript bash css html" | tr ' ' '\n'`
utils=`echo "jq find xargs tmux nvim curl less" | tr ' ' '\n'`

# set the fzf command if in tmux or not
fzf_cmd="fzf"
if [[ ! -z $TMUX ]]; then
  fzf_cmd="fzf-tmux -h 80% -w 50%"
fi

# select the tool in fzf
selected=`printf "$languages\n$utils" | $fzf_cmd`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

# process the selected tool differ between utils and languages
sep="~"
if printf "$languages" | grep -qs "$selected"; then
  query=`echo $query | tr ' ' '+'`
  sep="/"
fi

curl_cht "curl -s cht.sh/$selected$sep$query | less -R"

