[tools]
"aqua:junegunn/fzf/fzf-tmux" = "latest"
fzf = "0.74.4"
gh = "2.101.0"
go = "latest"
java = "zulu-25"
lazygit = "0.65.1"
maven = "latest"
neovim = "0.12.5"
ripgrep = "15.2.0"
starship = "latest"
tmux = "latest"
zoxide = "0.10.0"
"cargo:worktrunk" = "latest"
